# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Web UI Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    # - name: Build with Gradle
    #   uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
    #   with:
    #     arguments: build

    # install chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
      
    # setup graldew
    - name: Setup gradlew
      run: chmod +x gradlew 
      
    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew testCucumber

    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports
      
    # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: reports
