
name: Web UI Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  running-automation:
    runs-on: ubuntu-latest

    steps:
    # install repo
    - uses: actions/checkout@v3
    
    # install java
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.3.0

    # setup graldew
    - name: Setup gradlew
      run: chmod +x gradlew

    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew testCucumber

    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports

    # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_DIR: reports
        
    # - name: Build with Gradle
    #   uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
    #   with:
    #     arguments: build
