# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Web UI Automation Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  web-ui-automation:
    runs-on: ubuntu-latest

    # setup repo
    steps:
    - uses: actions/checkout@v3

    # setup java
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    
    # - name: Build with Gradle
    #   uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
    #   with:
    #     arguments: build

    # setup browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.3.0

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # Execute gradle command for running cucumber test
    - name: Execute Cucumber Test
      run: ./gradlew testCucumber

    # Archive Test Result 
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.3
      if: always()
      with: 
          name: Cucumber test
          path: reports

    # Deploy to GitHub Pages 
    - name: GitHub Pages action
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
          personal_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: reports
